---
- name: Execute Cisco IOS command
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: show hostname_before
      ios_command:
        commands: show running-config | include hostname
      register: result_old

    - name: show hostname_before_var
      debug:
        var: result_old.stdout_lines

    - name: 修改主机名
      ios_config:
       lines:
       - hostname {{ hostname }}
      vars:
       hostname: "{{ hostvars[inventory_hostname]['hostname'] }}"
      register: config_result
      delegate_to: "{{ inventory_hostname }}"

    - name: 显示结果
      debug:
        var: config_result.stdout_lines

    
    # - name: store result
    #   copy:
    #     content: "{{ result.stdout }}"
    #     dest: /.ansible/tmp/file.txt
